pages:
  image: node:latest # 针对前端，选择合适的node镜像
  stage: build
  script:
    - echo "start build..."
    - echo $(pwd)
  cache:
    paths:
    - node_modules/
  artifacts:
    paths:
    - public
  tags:
    - gitlab-org
