image: node:18-alpine # use nodejs v18 LTS
cache:
  paths:
    - node_modules/

before_script:
  - ls

pages:
  script:
    - ls
  artifacts:
    paths:
      - public
  tags:
    - gitlab-org
      
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH