image: node:18-alpine # use nodejs v18 LTS

before_script:
  - echo "start"

pages:
  script:
    - echo "stop"
  artifacts:
    paths:
    - /zzx
    - /tv
  tags:
    - gitlab-org
      
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH